### ISSUE TITLE
Build with Actions

### ISSUE THREAD

**Issue by seanshpark** [seanshpark/netron#8]
To build for all platforms with Actions.

**Comment by seanshpark** [comment]
Upload artifacts;
```
      - name: Upload artifacts
        uses: Actions/upload-artifact@v3
        with:
          name: (?)
          path: (?)
          retention-days: (?)
```
